// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Xacte.Patient.Data.Generated;

public partial class InscriptionPatient
{
    public string InscriptionId { get; set; }

    public string Nam { get; set; }

    public string Nom { get; set; }

    public string Prenom { get; set; }
}